/*
 * This source file was generated by the Gradle 'init' task
 */
package repro.java.issue;

import static org.testng.Assert.assertEquals;

import org.testng.annotations.Test;

public class AppTest {
    @Test
    public void appHasAGreeting() {
        assertEquals(new App().getGreeting(), "Hello World!");
    }
}
